[package]
name = "celaut_payment"
version = "0.1.0"
edition = "2021"

[dependencies]
basis_store = { path = "../basis_store" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tracing = "0.1"
hex = "0.4"
